overrides:
  ceph:
    conf:
      mgr:
        debug client: 10

tasks:
  - cephfs_test_runner:
      modules:
        - tasks.cephfs.test_mirroring.TestMirroring.test_cephfs_mirror_cancel_mirroring_and_readd
