overrides:
  ceph:
    log-ignorelist:
      - overall HEALTH_
      - \(MON_DOWN\)
      - Throttler Limit has been hit. Some message processing may be significantly delayed.
tasks:
- mon_thrash:
    check_mds_failover: True
    revive_delay: 20
    thrash_delay: 10
